[COMMON]
DisplayConsole = 1

; External camera tweaks.
; Minimal game version - 6.7
[EXT_CAMERA]
HookEnabled = 1
interp_coeff   = 0.40
rotation_coeff = 0.70


; Workaround to fix AI-car behaviour on narrow roads.
; Minimal game version - 8.2
[AI_CAR]
HookEnabled = 1
loop_dist   = 25.0
loop_incr   = 05.0
max_width   = 10.0

; Corrects semi-trailers physics behaviour.
; Minimal game version - 8.2
[STRAILER_PHY]
HookEnabled = 1
tractor_steer_coeff = 1.7
tractor_coeff  = 0.1
strailer_coeff = 4.5

[PATCHES]
; Fixes 1-second freezes when entering Greystone and improves loading times.
; Minimal game version - 6.6
QueueSortingFix = 1

; Fixes dust particles direction.
; Minimal game version - 7.0
DustParticlesFix = 1

; Fixes mirror drawing problems when game is running in 16x9.
; Minimal game version - 7.1
MirrorsFix = 1

; Adjustes collision constants to reduce "sticking" between dynamic objects.
; Minimal game version - 7.1
CollisionsFix = 1

; Fixes cabin positions bug.
; Minimal game version - 8.0/1.3
CabinCamFix = 1

; Fixes some bugs of upgrade system.
; Minimal game version - 8.0/1.3
TechSystemFix = 1